# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TimeboundIam < Formula
  desc "Temporary AWS credential broker that runs as an MCP server"
  homepage "https://github.com/builder-magic/timebound-iam"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/builder-magic/timebound-iam/releases/download/v0.6.0/timebound-iam_0.6.0_darwin_amd64.tar.gz"
      sha256 "95cf43a61a9bee43ba08561494b040285730f75f4e1c9577c6e50643d8c4fe13"

      define_method(:install) do
        bin.install "timebound-iam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/builder-magic/timebound-iam/releases/download/v0.6.0/timebound-iam_0.6.0_darwin_arm64.tar.gz"
      sha256 "8e29a13a4a23dcf75fb413bc51e1f49b9e30c7afcba08dcece7c922182dc8377"

      define_method(:install) do
        bin.install "timebound-iam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/builder-magic/timebound-iam/releases/download/v0.6.0/timebound-iam_0.6.0_linux_amd64.tar.gz"
      sha256 "fc7e487fc7d60780f8df7d82873a09923eb424cef76b933e4b43ac4931ca3e88"
      define_method(:install) do
        bin.install "timebound-iam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/builder-magic/timebound-iam/releases/download/v0.6.0/timebound-iam_0.6.0_linux_arm64.tar.gz"
      sha256 "cee72519a544cf51efbf83bbda386d8d3579187dfd79f02ca15a7d0ed6940e83"
      define_method(:install) do
        bin.install "timebound-iam"
      end
    end
  end
end
